# Generated by Django 5.0.1 on 2024-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Patrocinador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrocinador',
            old_name='idade',
            new_name='cnpj',
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='atividade',
            field=models.TextField(default='Valor padrão', max_length=1000),
        ),
    ]
